# Generated by Django 2.0.5 on 2018-05-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_dc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='value',
        ),
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transactions',
            name='date',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transactions',
            name='tid',
            field=models.CharField(default='tid', max_length=64),
        ),
    ]
