# Generated by Django 2.0.5 on 2018-05-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_dc', '0003_auto_20180513_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='amount',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='date',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='tid',
            new_name='tx_index',
        ),
    ]
